
[[constraint]]
  name = "github.com/apache/thrift"
 # revision = "24918abba929282"
  version = "0.12.0"
  source = "github.com/apache/thrift"


[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"


[prune]
  go-tests = true
  unused-packages = true
